### PR TITLE
fix for issue #5

### PR DESCRIPTION
**Pull request by binarytemple**
fix for issue #5

### CODE REVIEW

**Comment by anildigital** [comment]
What's the fix? I did not get. I am still getting the same error.

Are you saying that I should point to GitHub repo?

**Comment by ghost** [comment]
No, you are just missing some configuration in your config file:

```
config :haikunator, :adjectives, ~w(
  autumn hidden bitter misty silent empty dry dark summer
  icy delicate quiet white cool spring winter patient
  twilight dawn crimson wispy weathered blue billowing
  broken cold damp falling frosty green long late lingering
  bold little morning muddy old red rough still small
  sparkling throbbing shy wandering withered wild black
  young holy solitary fragrant aged snowy proud floral
  restless divine polished ancient purple lively nameless
)


config :haikunator, :nouns, ~w(
   waterfall river breeze moon rain wind sea morning
   snow lake sunset pine shadow leaf dawn glitter forest
   hill cloud meadow sun glade bird brook butterfly
   bush dew dust field fire flower firefly feather grass
   haze mountain night pond darkness snowflake silence
   sound sky shape surf thunder violet water wildflower
   wave water resonance sun wood dream cherry tree fog
   frost voice paper frog smoke star
)
```

The error is a somewhat unhelpful, but all my fix would have done is to cause further confusion.

**Comment by autodidaddict** [comment]
I just got this same error from a brand new installation, copied that configuration into my project, and I still get this error.

**Comment by ghost** [comment]
@autodidaddict  You need to set (via your config files) or `Application.put_env/3` the lists of adjectives and nouns used by haikunator. Haikunator uses these values at compile time, so no config == nil exception or suchlike. Here's an example of it a fresh project checkout working.

```
iex(31)> Haikunator.build
"ancient-darkness-530"
iex(32)> Application.put_env(:haikunator, :adjectives, ~w( smelly damp cheesy))
:ok
iex(33)> Application.put_env(:haikunator, :nouns, ~w( cat rat dog))
:ok
iex(34)> recompile(force: true)
Compiling 1 file (.ex)
Generated haikunator app
:ok
iex(35)> Haikunator.build
"smelly-rat-9334"
```

**Pull request closed without merging**
